### PR TITLE
Gsoc1 plot spectra

### PR DESCRIPTION
**Pull request by Tejasvigupta**
I have done some changes in the `plotSpectra`  function and before I move ahead I want you to have a look.

### CODE REVIEW

**Review by bryanhanson — COMMENTED** [review]
Generally, there are things you can combine to get a leaner and faster code.  Some specifics:
1. `mode` is a function in name in R so probably best not to use it as a variable name, in this case for consistency I'd use `go` like we did elsewhere.
2. You don't need `df <- 0` as you immediately overwrite it.
3. For `names(df) <- c("WaveNumber", name)` you can remove lines 130-136 and just do `names(df) <- c("WaveNumber", spectra$names[which])`  Do the same thing for the color vector (later in file).  You can do both in the same loop.
4. You can eliminate `    spectrum <- spectra$data[which[1], ] * amplify` and just add the `amplify` argument to `i <- (spectra$data[i, ])` (line 124) since you will need to amplify all of them eventually anyway. In fact, while you are doing this `cbind` step you should go ahead and bring in the count and offset operations that you have lower for `lab.y`.  That way you get all the data ready in one pass through a loop (faster).  I think you can compute the `lab.y` in the same loop if you move a few things around.
5. It has been a while since I have worked with `ggplot2` in a non-trivial way, but I think you might be able to add `color` to `df` before melting it and then you can avoid the manual color scale call.   And probably `group` as well to ensure everything matches up correctly.
6. Make sure this will actually return `p` -- since this is inside an `if` condition one might have to assign a return variable at the beginning and then explicitly return it at the end (not certain though, maybe it will work as written).
7. You probably need to have a `print(p)` in there to make the plot appear automatically (again, maybe not).
8. I did not look in detail at the legend set up. Next round!

**Review by bryanhanson — COMMENTED** [review]
A few more things. Please don't be discouraged by the number of changes needed!  Things will go faster after we get this first function working well and cleaned up.

1. Organize the flow: put all steps of constructing `df` together, and all steps of the label coordinates together.  Right now, they are intermixed.  Use headers to briefly relate the intent, like `# Set up data frame for plotting` and `# Compute label positions`. Related: at line 167 you are using `lab.pos` and it should probably be `lab.x` for consistency.
2. In general, avoid setting up an empty vector like `lab.y <- c()` These start out with a data type of `NULL` and as soon as you add something to it the data type will change and this has some memory overhead we can avoid.  Instead, do `lab.y <- c(NA_real_)` for example, or `NA_character_` if you are using string data.  Then after you populate the vector, remove the initial `NA` with `lab.y <- lab.y[-1]`.  Though this is some extra coding it runs faster and the programmer's intention is clearer -- R is not "type safe" which has pros and cons.
3. Instead of `WaveNumber`, please use `Frequency` (wavenumber is a specific unit for frequency, we should keep it generic even though the name of this variable doesn't affect the plot visually).
4. _Fix Last,_ perhaps even after another review or two: the legend is currently doing the same thing as `lab.pos`, namely identifying each spectrum by color.  It should actually be reporting the colors assigned to each group (each group can have multiple spectra of the same color; e.g. replicates of control and treatment samples).
5. After a little experimentation, I think the way you are handling the color manually is the best, but please verify we are getting the correct colors by comparing the `base` version with the `ggplot2` version.
6. Documentation 1: The return value entry needs to be a bulleted list giving the return value for each possible graphics option.
7. Documentation 2: Once the function is working as desired we need a basic example using `ggplot2` and then an example showing how the user can update the theme.

**Review by bryanhanson — CHANGES_REQUESTED** [review]
Looking really good!  This is interesting for me to review this, because it invariably makes me read my code for `base`, which was written a long time ago.  This leads to the first item:

1. In the whole file rename `spec.index` to `freq.index` -- this is a name I chose ages ago and on re-reading I think `freq.index` better describes what this variable is (one has to program defensively, thinking about how the code will look to others or oneself in the future).
2. In the `cbind` action when creating `df`, I noticed that the index to the loop and the data itself are both called `i`.  I think we got lucky this works at all.  Change the `i` that is the current spectrum to `spec` and it will be clearer.  Also, there is an extra set of ()'s around the first term in `i <- ((spectra$data[i, ]) + (count * offset)) * amplify`.
3. Remove all the `leg.loc` stuff in the `ggplot2` option since we won't be showing a legend for now and when we do, we'll do it differently.
4. This line: `lab.y <- c(lab.y, df[, i][spec.index] + 0.1)` I think you must be using the 0.1 as a fudge factor to get the label above the data.  I had to study why/how it works in the `base` version; it's `pos` that takes care of this, but there is no such feature in `annotate`.  So your approach is the correct one but we can't chosee a single number, that would be fragile as the y scale of the data changes.  So instead of using 0.1, compute something like 5% of the height of each spectrum and use that instead.  That will make the offset a bit different for each spectrum which might end up "ugly" but we can fine tune that later.

With these changes this can be merged.  As you finish functions, I will follow behind you to fine tune the documentation, which is a critical component for user-friendliness.  As a "recovering" professor I tend to edit a lot!

**Review by bryanhanson — COMMENTED** [review]
These changes look very good. Holding for a slightly different approach to the legend issue.

**Review by bryanhanson — COMMENTED** [review]
Excellent! You found a way to use the "raw" grid command (the grob) and incorporate them into the `ggplot2` paradigm.  I like this.  Now, let's think about how we want the user to tell us about the legend position. Obviously they will give us `leg.loc = list(x = something, y = something)` and the values should be on `[0, 1]` But what will that location specify?  The center of the grob?  The top center of the grob?  Some corner of the grob?  Please look into what you can control easily regarding the positioning.  I think if this was pure `grid` pushing a viewport the default would be dead center.  But see what you can find, and adjust the code accordingly.  Then we'll think about the base case.

**Review by bryanhanson — COMMENTED** [review]
_Feel free to leave this until Monday!_

I think you've got the user provided `xlim` case correct!  But, and I may have missed it, it looks like we lost the code for when the user does not give `xlim`.  Simple to add back though: before the `xlim` in args code, calc `y.min`, `y.max`, `x.min` and `x.max` (the last two from `spectra$freq` like you did before).  Then, if the user has given `xlim` update it / overwrite it as you have it now (you don't need to touch `y.min` and `y.max` they are the same regardless).

**Comment by bryanhanson** [comment]
One final detail:  This code:
```
y.min <-yrange[1]
y.max <-yrange[2]
```
needs to move up, above and outside the `if ("xlim" %in% names(args))` line. Otherwise if the user _doesn't_ give `xlim` `y.min` and `y.max` will be undefined.

**Comment by Tejasvigupta** [comment]
My bad!

**Review by bryanhanson — APPROVED** [review]
Here we go!  Time to merge.

**Pull request merged**
